name: CI
'on':
  push:
  workflow_dispatch:
  #schedule:
    # every sunday at 00:00
    #- cron: "0 0 * * 0"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy-site:
    runs-on: ubuntu-latest
    container: node:19-bullseye

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: install npm deps
        run: npm install

      - name: run the linter
        run: node scripts/lint-ci.js

      - name: upload lint results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: lint-results
          path: lint-results.xml

      - name: run the tests
        run: npm run test -- --passWithNoTests --reporters=default --reporters=jest-junit

      - name: upload test results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: junit.xml

      - name: build the site
        run: npm run build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
